#!/bin/bash

set -e

VERSION=0.0.3

BUILDDIR=build/msieve-shared/$VERSION/$TARGET
rm -rf $BUILDDIR
mkdir -p $BUILDDIR

git clone cache/msieve-shared $BUILDDIR
git -C $BUILDDIR checkout v$VERSION
patch $BUILDDIR/Makefile patch/msieve-shared/$VERSION/$TARGET/Makefile.patch
cp cache/PrimeSieve.jl/deps/src/localmsieve/msieveshared.c $BUILDDIR

pushd $BUILDDIR
make ECM=1 NO_ZLIB=1 msieveshared
popd

cp $BUILDDIR/msieve.exe $OUTPUTDIR
cp $BUILDDIR/libsmsieve.dll $OUTPUTDIR
