#!/bin/bash

set -e

VERSION=0.0.3
TARGET=x86_64-w64-mingw32

BUILDDIR=src/msieve-shared/$VERSION/$TARGET
INSTALLDIR=$PWD/local
OUTPUTDIR=lib/msieve-shared/$VERSION/$TARGET

rm -rf $BUILDDIR
rm -rf $OUTPUTDIR

mkdir -p $BUILDDIR
mkdir -p $INSTALLDIR
mkdir -p $OUTPUTDIR

git clone cache/msieve-shared $BUILDDIR
git -C $BUILDDIR checkout v$VERSION
cp patch/msieve-shared/$VERSION/$TARGET/Makefile $BUILDDIR
cp cache/PrimeSieve.jl/deps/src/localmsieve/msieveshared.c $BUILDDIR

pushd $BUILDDIR
make ECM=1 NO_ZLIB=1 msieveshared
popd

cp $BUILDDIR/libsmsieve.dll $OUTPUTDIR
