#!/usr/bin/env bash

set -e

VERSION=master

BUILDDIR=build/cprimecount/$VERSION/$TARGET
rm -rf ${BUILDDIR:?}
mkdir -p $BUILDDIR

cp -r cache/PrimeSieve.jl/deps/src/cprimecount/* $BUILDDIR

pushd $BUILDDIR
$TARGET-g++ $CXXFLAGS -Wall -c -O2 -DDLL_BUILD=1 cprimecount.cpp -I$INSTALLDIR/include
# linking to primesieve not neccessary unless we want functions from primesieve.
$TARGET-g++ $CXXFLAGS -Wall -mwindows -shared cprimecount.o -o libcprimecount.dll -lstdc++ -L$INSTALLDIR/lib/ -lprimecount -lprimesieve
popd

cp $BUILDDIR/libcprimecount.dll $OUTPUTDIR
