#!/bin/bash

set -e

VERSION=2.9.0

BUILDDIR=build/pari/$VERSION/$TARGET
rm -rf ${BUILDDIR:?}
mkdir -p $BUILDDIR

git clone cache/pari $BUILDDIR
git -C $BUILDDIR checkout pari-$VERSION

if [ $TARGET = "x86_64-w64-mingw32" ]; then
   HOST=x86_64-mingw
   MAKEDIR="Omingw-x86_64"
else
   HOST=i686-mingw
   MAKEDIR="Omingw-i686"
fi

pushd $BUILDDIR
cp $INSTALLDIR/bin/libgmp-10.dll config/
RUNTEST=~/bin/runwine CC="$TARGET-gcc" CXX="$TARGET-g++" AR="$TARGET-ar" ./Configure --host=$HOST --prefix=$INSTALLDIR --with-gmp=$INSTALLDIR #--mt=pthread
cd $MAKEDIR
make -j4 gp
make install
popd

#cp /usr/$TARGET/lib/libwinpthread-1.dll $OUTPUTDIR
cp $INSTALLDIR/bin/libpari.dll $OUTPUTDIR
