#!/usr/bin/env bash

set -e

VERSION=5.7.3

BUILDDIR=build/primesieve/$VERSION/$TARGET
rm -rf ${BUILDDIR:?}
mkdir -p $BUILDDIR

git clone cache/primesieve $BUILDDIR
git -C $BUILDDIR checkout v$VERSION

pushd $BUILDDIR
./autogen.sh --host=$TARGET
# CXXFLAGS="-static -static-libgcc -static-libstdc++" ./configure --host=$TARGET --prefix=$INSTALLDIR
./configure --host=$TARGET --prefix=$INSTALLDIR
make
make install
popd

cp /usr/lib/gcc/$TARGET/6.2-win32/libgcc_s_seh-1.dll $OUTPUTDIR || cp /usr/lib/gcc/$TARGET/6.2-win32/libgcc_s_sjlj-1.dll $OUTPUTDIR
cp /usr/lib/gcc/$TARGET/6.2-win32/libstdc++-6.dll $OUTPUTDIR
cp /usr/lib/gcc/$TARGET/6.2-win32/libgomp-1.dll $OUTPUTDIR
cp /usr/$TARGET/lib/libwinpthread-1.dll $OUTPUTDIR
cp $INSTALLDIR/bin/libprimesieve-7.dll $OUTPUTDIR
cp $INSTALLDIR/bin/primesieve.exe $OUTPUTDIR
