#!/usr/bin/env bash

set -e

VERSION=2.6

BUILDDIR=build/primecount/$VERSION/$TARGET
rm -rf ${BUILDDIR:?}
mkdir -p $BUILDDIR

git clone cache/primecount $BUILDDIR
git -C $BUILDDIR checkout v$VERSION

pushd $BUILDDIR
./autogen.sh --host=$TARGET
# CXXFLAGS="-static -static-libgcc -static-libstdc++" CPPFLAGS="-I../../../../local/include/" LDFLAGS="-L../../../../local/lib/" ./configure --host=$TARGET --prefix=$INSTALLDIR # --disable-libdivide
CPPFLAGS="-I../../../../local/include/" LDFLAGS="-L../../../../local/lib/" ./configure --host=$TARGET --prefix=$INSTALLDIR # --disable-libdivide
make
make install
popd

cp /usr/lib/gcc/$TARGET/6.2-win32/libgcc_s_seh-1.dll $OUTPUTDIR || cp /usr/lib/gcc/$TARGET/6.2-win32/libgcc_s_sjlj-1.dll $OUTPUTDIR
cp /usr/lib/gcc/$TARGET/6.2-win32/libstdc++-6.dll $OUTPUTDIR
cp /usr/lib/gcc/$TARGET/6.2-win32/libgomp-1.dll $OUTPUTDIR
cp /usr/$TARGET/lib/libwinpthread-1.dll $OUTPUTDIR
cp $INSTALLDIR/bin/libprimecount-4.dll $OUTPUTDIR
cp $INSTALLDIR/bin/libprimesieve-7.dll $OUTPUTDIR
cp $INSTALLDIR/bin/primecount.exe $OUTPUTDIR
