#!/bin/bash

set -e

VERSION=6.1.1

BUILDDIR=build/gmp/$VERSION/$TARGET
rm -rf ${BUILDDIR:?}
mkdir -p $BUILDDIR

tar xjf cache/gmp-$VERSION.tar.bz2 -C $BUILDDIR --strip-components=1

pushd $BUILDDIR
./configure --host=$TARGET --prefix=$INSTALLDIR --disable-static --enable-shared
make -j4
make install
popd

cp $INSTALLDIR/bin/libgmp-10.dll $OUTPUTDIR
